name: Validate AZD template
on:
  push:
    branches: [main, develop]
    paths:
      - 'infra/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@preview
        id: msdo
        continue-on-error: true
        with:
          tools: templateanalyzer

      - name: Upload alerts to Security tab
        if: github.repository == 'Azure-Samples/azure-search-openai-javascript'
        uses: github/codeql-action/upload-sarif@b8d3b6e8af63cde30bdc382c0bc28114f4346c88 # v2.28.1
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}